### ISSUE TITLE
Does not work with recent versions of Magento

### ISSUE THREAD

**Issue by quickshiftin** [controlaltdelete-nl/magento2-live-reload#1]
The composer constraint is preventing use in newer versions of Magento. Can we simply make [this change](https://github.com/quickshiftin/magento2-live-reload/commit/85b107127b56b54b7fdba81a7935a41df48bd3b1)

```
        "magento/framework": "^100.1|^101.0"
        "magento/framework": "^100.1|^101.0|^102.0"
```

**Comment by michielgerritsen** [comment]
Hi @quickshiftin,

Thanks for pointing this out. Could you make a PR of that? I will merge it so you will be able to install.

**Comment by quickshiftin** [comment]
Thx! Would you mind updating Packagist as well?

**Comment by michielgerritsen** [comment]
I needed to tag it first, it just is updated.

**Comment by quickshiftin** [comment]
Thanks for the quick update @michielgerritsen !
